name: Update t2gentoo-kernel

on:
  schedule:
    - cron: "0 2 * * *" # Esegue ogni giorno alle 2:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-ebuilds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout overlay
        uses: actions/checkout@v4
        with:
          path: t2-overlay

      - name: Run update inside Gentoo container
        env:
          KERNEL_BRANCHES: "${{ vars.KERNEL_BRANCHES }}"
        run: |
          set -e
          docker --version
          docker run --rm \
            -v ${{ github.workspace }}/t2-overlay:/workspace \
            -w /workspace \
            gentoo/stage3:latest \
            /bin/bash -c "set -e; emerge-webrsync -q; emerge -qg dev-vcs/git; python3 scripts/update_kernel.py"

      - name: Commit and push changes
        run: |
          cd t2-overlay
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add sys-kernel/t2gentoo-kernel/
          git add virtual/dist-kernel/


          if ! git diff --staged --quiet; then
            if [ -f commit_message.txt ]; then
              git commit -F commit_message.txt
              rm commit_message.txt
            else
              git commit -m "Auto-update t2gentoo-kernel ebuilds and manifests"
            fi
            git push
            echo "Changes pushed successfully."
          else
            echo "No changes to commit."
          fi
